### ISSUE TITLE
Header Consistency Between Item-Detail and List-View Pages

### ISSUE THREAD

**Issue by mikewolfd** [keeplist-io/keeplist-website#4]
**Description:**  
The header should have consistent text display between the item-detail view and the list view.

**Steps to Reproduce:**  
1. Visit the list view (e.g., `/profile/sashashilko/lists/go-to-chicago-restaurants/`).  
2. Click into an item (e.g., `/profile/sashashilko/lists/go-to-chicago-restaurants/elske/`).  
3. Compare the header display on both pages.

**Expected Behavior:**  
The header text display should be consistent across both views.

**Acceptance Criteria:**  
- [ ] Headers on item-detail and list-view pages have matching text styling and layout.

**Comment by amvitez** [comment]
@mikewolfd 
Actually, the designs don't have a header on the Item-Detail page. Not sure if you added it intentionally with the refactor, but I think showing which list you are drilled into is a good idea. So layout wise, how should the two headers compare?
